### ISSUE TITLE
Whole-program analysis

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-unused#22]
Consider if it's worth providing a flag for whole-program analysis that also checks exported identifiers and if they're being used in any known package.

**Comment by jimmyfrasche** [comment]
It could be noisy for vendored code. You're unlikely to use 100% of the API surface of a dependency or all packages in a vendored repository. 

It might be best to treat an entire vendored repository as a unit, rather than its packages or their identifiers. So if one identifier in vendor.com/foo is used just once and nothing in vendor.com/bar is used at all, mark vendor.com as used.

One place this would be quite useful and consistently applicable is internal/ packages. They have limited visibility and exist only to serve the packages that can see them, so if they export something unused within that limited scope, it's definitely unused. An easy case would be if no packages in that scope import them at all.

The internal and vendor cases could even be on by default whenever  /... is used.

**Comment by dominikh** [comment]
Thanks. I hadn't considered the vendor issue (though I probably would've noticed eventually). I've added it to the list of things to consider.

FWIW, I'll most likely implement this feature. The fix for #27 (changing to a proper graph-based approach) makes implementing this even more trivial, as it just changes the set of roots (entry points to the package) that we record.

**Comment by dmitshur** [comment]
> if they're being used in any known package.

In one's GOPATH, yes?

**Comment by dominikh** [comment]
Regarding vendoring: use `$(go list ./... | grep -v /vendor/)` – the idiom that's used with all the other tools (such as `go test`), too.

> In one's GOPATH, yes?

Any packages you pass to the tool.

`unused foo bar` will check if the identifiers declared in foo and bar are used by foo or bar (or by interfaces declared in any of the dependencies).
