### ISSUE TITLE
Exported fields not recognized as unused

### ISSUE THREAD

**Issue by mdempsky** [dominikh/go-unused#46]
Running

```
unused -exported cmd/internal/obj
```

does not identify cmd/internal/obj.Link.Etextp as unused.

**Comment by dominikh** [comment]
@mdempsky Can you tell me a specific commit in the Go project at which it should be considered unused?

**Comment by dominikh** [comment]
So, right now, `unused` considers all exported fields as used, always. IIRC this was done because of reflection, in particular marshaling of structs. 

It might be possible to tweak the rule and only mark those fields as used when an instance of the type is assigned to an interface value. I'll play around with that.

**Comment by mdempsky** [comment]
If you're worried about reflection accessing fields, it's not sufficient to just check for T itself being stored in an interface.  You'll also need to handle other types that might reference values of type T, and possibly indirectly.

FWIW, for my use case (working on the Go compiler), reflection is relatively rare (probably just interface type assertions, actually). I'd be happy with a flag to tell unused to just disregard the possibility of reflection accessing a field.

**Comment by dominikh** [comment]
> If you're worried about reflection accessing fields, it's not sufficient to just check for T itself being stored in an interface. You'll also need to handle other types that might reference values of type T, and possibly indirectly.

Good point. `unused` is generally good about tracking indirect access (the used/unused state of each identifier is represented in a graph), but we'd still require changes to a fair bit of code. We're not exactly doing proper data flow analysis, primarily because `-exported` was added at a later point, so whole program analysis is just based around some safe assumptions, at the risk of more false negatives.

> FWIW, for my use case (working on the Go compiler), reflection is relatively rare (probably just interface type assertions, actually). I'd be happy with a flag to tell unused to just disregard the possibility of reflection accessing a field.

Yeah, I'm tempted to just add that flag for now. I won't have time to make big changes to `unused` for a while (smaller changes and bug fixes will be fine, though.)

**Comment by dominikh** [comment]
There, I've added `-reflect` for the time being, which defaults to on, so you will want `-reflect=false`. I'll leave this issue open until a real fix is made.
