### ISSUE TITLE
How to check net/rpc based code?

### ISSUE THREAD

**Issue by powerman** [dominikh/go-unused#47]
With net/rpc and similar packages we've some type which methods will be called using reflect for incoming RPC calls. So, these methods and their dependencies shouldn't be counted as unused. How to check such code?

**Comment by dominikh** [comment]
Exported methods on used types are always considered used. And since net/rpc requires passing an instance of the type to rpc.Register, the type should also be used. As long as you're not using the `-exported` flag, unused should already behave correctly. For `-exported`, we may need to add a special case for net/rpc.

**Comment by powerman** [comment]
Yes, I'm using `-exported`. How we can work around this case?

**Comment by dominikh** [comment]
> With net/rpc and similar packages

Can you tell me which the "similar packages" are?

**Comment by powerman** [comment]
> Can you tell me which the "similar packages" are?

Well, I was talking about net/rpc codecs like net/rpc/jsonrpc and https://godoc.org/github.com/powerman/rpc-codec/jsonrpc2 - not sure is this makes any difference for unused.

**Comment by dominikh** [comment]
I don't think it matters, as the type will be registered with net/rpc, not the codecs. I have pushed a change that explicitly adds support for net/rpc – please check if the new version fixes your issue.

**Comment by powerman** [comment]
Yeah, at a glance looks like it works! Thanks!
