### ISSUE TITLE
undefined: build.AllowVendor

### ISSUE THREAD

**Issue by quii** [dominikh/go-unused#5]
When I try and go get

``` bash
Chriss-Air:mockingjay-server quii$ go get honnef.co/go/unused/cmd/unused
# golang.org/x/tools/go/buildutil
../../../golang.org/x/tools/go/buildutil/buildutil_go16.go:14: undefined: build.AllowVendor
```

**Comment by dmitshur** [comment]
One problem is you have an outdated dependency.

Try:

```
go get -u honnef.co/go/unused/cmd/unused
```

The -u flag causes `go get` to to update all dependencies. You should learn more about it here:

https://golang.org/cmd/go/#hdr-Download_and_install_packages_and_dependencies

That should help, but may not completely resolve your issue. If you're still having problems after above, it might be because you have an outdated version of Go installed. What does `go version` print? If it's something less than `go1.6`, you should update to Go 1.6, the current stable release of Go:

https://golang.org/doc/install

**Comment by dominikh** [comment]
I'll close this issue. shurcooL is right about an outdated dependency, so there's nothing here for us to do.
